blank_issues_enabled: false
contact_links:
  - name: GitHub Support
    url: https://support.github.com/contact
    about: Contact Support if you're having trouble with your GitHub account.
/storage/emulated/0/Pictures/Messenger/
